import esbuild from 'esbuild';
import process from 'process';
import nodeBuiltins from './esbuild-node-builtins.mjs';
import { watch } from 'fs';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import copyFilesPlugin from './esbuild-copy-files.mjs';

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = process.argv[2] === 'production';
const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PLUGIN_ID = 'language-recall';
const INSTALL_FILES = ['main.js', 'styles.css', 'manifest.json'];

/**
 * Resolve the Obsidian install dir to overwrite on each build.
 * Override with OBSIDIAN_PLUGIN_DIR or env.mjs `obsidianExportPath`.
 */
async function resolveObsidianOutDir() {
  if (process.env.OBSIDIAN_PLUGIN_DIR) {
    return path.resolve(process.env.OBSIDIAN_PLUGIN_DIR);
  }
  try {
    const env = await import('./env.mjs');
    if (env.obsidianExportPath) {
      return path.resolve(env.obsidianExportPath);
    }
  } catch {
    // env.mjs is optional
  }
  return path.resolve(__dirname, `../../../.obsidian/plugins/${PLUGIN_ID}`);
}

function copyToObsidian(outDir) {
  fs.mkdirSync(outDir, { recursive: true });
  for (const file of INSTALL_FILES) {
    const src = path.resolve(__dirname, file);
    if (!fs.existsSync(src)) continue;
    fs.copyFileSync(src, path.join(outDir, file));
  }
  console.log(`Copied ${INSTALL_FILES.join(', ')} → ${outDir}`);
}

const outDir = await resolveObsidianOutDir();

const buildOptions = {
  banner: {
    js: banner,
  },
  entryPoints: ['src/main.ts'],
  bundle: true,
  external: [
    'obsidian',
    'electron',
    '@codemirror/autocomplete',
    '@codemirror/closebrackets',
    '@codemirror/collab',
    '@codemirror/commands',
    '@codemirror/comment',
    '@codemirror/fold',
    '@codemirror/gutter',
    '@codemirror/highlight',
    '@codemirror/history',
    '@codemirror/language',
    '@codemirror/lint',
    '@codemirror/matchbrackets',
    '@codemirror/panel',
    '@codemirror/rangeset',
    '@codemirror/rectangular-selection',
    '@codemirror/search',
    '@codemirror/state',
    '@codemirror/stream-parser',
    '@codemirror/text',
    '@codemirror/tooltip',
    '@codemirror/view',
    '@lezer/common',
    '@lezer/highlight',
    '@lezer/lr',
    ...nodeBuiltins,
  ],
  format: 'cjs',
  target: 'es2016',
  logLevel: 'info',
  sourcemap: prod ? false : 'inline',
  treeShaking: true,
  outfile: 'main.js',
  plugins: [
    copyFilesPlugin({
      // Keep root styles.css in sync for release artifacts
      './src/styles.css': './styles.css',
    }),
    {
      name: 'copy-to-obsidian',
      setup(build) {
        build.onEnd((result) => {
          if (result.errors.length > 0) return;
          copyToObsidian(outDir);
        });
      },
    },
  ],
};

if (prod) {
  esbuild.build(buildOptions).catch(() => process.exit(1));
} else {
  (async () => {
    const ctx = await esbuild.context(buildOptions);
    await ctx.watch();

    console.log(`Watching for changes; install dir: ${outDir}`);

    watch('./src', { recursive: true }, async (eventType, filename) => {
      if (filename && filename.endsWith('.css') && eventType === 'change') {
        await ctx.rebuild();
      }
    });
  })().catch(() => process.exit(1));
}
